//============================================================================
// Author      : T. Thomas (TdotThomas@SpaceAgeMinds.com)
// Copyright   : Copyright 2016 T. Thomas. All rights reserved. (See LICENSE)
// Description : Ansible Playbook for Initial Server Setup.
// Name        : InitialServerSetup
// Version     : Alpha
// Compliation : N/A
// Execution   : 
//=====================================================================================================================
---
- hosts: ExampleDotCom
  remote_user: root
  vars_prompt:
    - name: "User"
      prompt: "Enter Server Administrator's Username"
    - name: "Password"
      prompt: "Enter Server Administrator's Password"
      private: yes
  tasks:

    - name: User Setup Task
      include: tasks/UserSetup.yml

# Software (Install, Update, and Configure)
# Update all installed packages to the latest version
    - name: Package Update Task
      include: tasks/PackageUpdate.yml

# Installing Software
    - name: Installing software.
      include: tasks/PackageInstall.yml

    - name: Removing Software 
      include: tasks/PackageUninstall.yml

    - name: Autoremove unused packages
      command: apt-get -y autoremove
      register: autoremove_output
      changed_when: "'The following packages will be REMOVED' in autoremove_output.stdout"

# Package Update and Install End

# Software Configure Start
# Setting up IPTabbles
# Software Configure End

# Handlers Start
  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
# Handlers End
