//============================================================================
// Author      : T. Thomas (TdotThomas@SpaceAgeMinds.com)
// Copyright   : Copyright 2016 T. Thomas. All rights reserved. (See LICENSE)
// Description : Ansible Playbook for Initial Server Setup.
// Name        : InitialServerSetup
// Version     : Alpha
// Compliation : N/A
// Execution   : 
//=====================================================================================================================
---
- hosts: ExampleDotCom
  remote_user: root
  vars_prompt:
    - name: "User"
      prompt: "Enter Server Administrator's Username"
    - name: "Password"
      prompt: "Enter Server Administrator's Password"
      private: yes
  tasks:

    - name: User Setup
      include: tasks/UserSetup.yml

# Software Update and Install Start
# Update all installed packages to the latest version
    - name: Update all installed packages to the latest version.
      apt:  upgrade=dist update_cache=yes

# Installing Software
    - name: Installing software.
      apt: name={{ item }} state=latest
      with_items:
        - fail2ban

    - name: Removing Software 
      apt: name={{ item }} state=absent purge=yes
      with_items:
        - exim4*
        - rpcbind*

    - name: Add cron job to update packages
      cron: name="Update Installed Packages" minute="0" weekday="0" hour="12" job="apt-get update && apt-get -y upgrade"

    - name: Autoremove unused packages
      command: apt-get -y autoremove
      register: autoremove_output
      changed_when: "'The following packages will be REMOVED' in autoremove_output.stdout"

# Package Update and Install End

# Software Configure Start
# Setting up IPTabbles
# Software Configure End

# Handlers Start
  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
# Handlers End
