# Set up Server Time (UTC)
---
- name: Configure the Timezone
  hosts: all
  tasks:
  
    - name: Update Timezone to Etc/UTC
      copy: content="Etc/UTC\n" dest=/etc/timezone owner=root group=root mode=0644
      sudo: true
      register: timezone

    - name: Reconfigure Timezone Data
      shell: dpkg-reconfigure -f noninteractive tzdata
      sudo: true
      when: timezone.changed
